### ISSUE TITLE
Widen graphql peer dep range

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/nexus-plugin-prisma#922]
## Description

The `graphql` peer dep range is way too conservative compared to what the plugin probably supports.

`@nexus/schema`'s peer dep range for `graphql` is `^0.12.0 || ^0.13.0 || ^14.0.0`, yet `nexus-plugin-prisma` only allows `^15.3.0`, which doesn’t make sense at all since technically, it means there’s no way for users to install `@nexus/schema` and `nexus-plugin-prisma` without having a peer dep warning for `graphql`

Once we've properly widened the peer dep range (including matrix tests for every version we claim to support), we should bring back the runtime peer dep check for `graphql` which was commented out on `nexus-plugin-prisma@0.23.1`

## TODO

- [ ] widen graphql peer dep range
- [ ] add matrix tests for every version claimed to be supported
- [ ] bring back runtime peer dep range check
